### ISSUE TITLE
Around what time will the pytorch version be there?

### ISSUE THREAD

**Issue by jma100** [lugiavn/revisiting-im2gps#1]
I've been having a lot of trouble with matcaffe. Would appreciate a pytorch version.

**Comment by lugiavn** [comment]
I planned to train a pytorch model, but that'll have to wait for a while since I left for summer already

Maybe you can try convert the model to pytorch, such as
https://github.com/CuriousCat-7/Caffe_torch_pytorch_converter

**Comment by jma100** [comment]
Thank you I will try that
